"""initial career content schema"""
from alembic import op
import sqlalchemy as sa

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    status = sa.Enum("DRAFT", "PUBLISHED", "ARCHIVED", name="status")
    for table, columns in [
        ("profiles", [sa.Column("id", sa.Integer, primary_key=True), sa.Column("full_name", sa.String(160), nullable=False), sa.Column("headline", sa.String(240), nullable=False), sa.Column("summary", sa.Text, nullable=False, server_default=""), sa.Column("location", sa.String(160), nullable=False, server_default=""), sa.Column("email", sa.String(320), nullable=False, server_default=""), sa.Column("website_url", sa.String(500), nullable=False, server_default=""), sa.Column("linkedin_url", sa.String(500), nullable=False, server_default=""), sa.Column("github_url", sa.String(500), nullable=False, server_default=""), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now())]),
        ("admin_users", [sa.Column("id", sa.Integer, primary_key=True), sa.Column("username", sa.String(160), unique=True, nullable=False), sa.Column("password_hash", sa.String(256), nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now())]),
    ]:
        op.create_table(table, *columns)
    op.create_table("experiences", sa.Column("id", sa.Integer, primary_key=True), sa.Column("profile_id", sa.Integer, sa.ForeignKey("profiles.id"), nullable=False), sa.Column("company_name", sa.String(200), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("location", sa.String(160), server_default=""), sa.Column("employment_type", sa.String(80), server_default=""), sa.Column("start_date", sa.Date), sa.Column("end_date", sa.Date), sa.Column("is_current", sa.Boolean, server_default=sa.false()), sa.Column("summary", sa.Text, server_default=""), sa.Column("sort_order", sa.Integer, server_default="0"), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("projects", sa.Column("id", sa.Integer, primary_key=True), sa.Column("profile_id", sa.Integer, sa.ForeignKey("profiles.id"), nullable=False), sa.Column("title", sa.String(200), nullable=False), sa.Column("short_description", sa.Text, server_default=""), sa.Column("long_description", sa.Text, server_default=""), sa.Column("project_url", sa.String(500), server_default=""), sa.Column("repo_url", sa.String(500), server_default=""), sa.Column("start_date", sa.Date), sa.Column("end_date", sa.Date), sa.Column("featured", sa.Boolean, server_default=sa.false()), sa.Column("sort_order", sa.Integer, server_default="0"), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("skill_categories", sa.Column("id", sa.Integer, primary_key=True), sa.Column("profile_id", sa.Integer, sa.ForeignKey("profiles.id"), nullable=False), sa.Column("name", sa.String(160), nullable=False), sa.Column("sort_order", sa.Integer, server_default="0"), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("skills", sa.Column("id", sa.Integer, primary_key=True), sa.Column("profile_id", sa.Integer, sa.ForeignKey("profiles.id"), nullable=False), sa.Column("category_id", sa.Integer, sa.ForeignKey("skill_categories.id")), sa.Column("name", sa.String(160), nullable=False), sa.Column("proficiency_level", sa.String(80), server_default=""), sa.Column("sort_order", sa.Integer, server_default="0"), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("education", sa.Column("id", sa.Integer, primary_key=True), sa.Column("profile_id", sa.Integer, sa.ForeignKey("profiles.id"), nullable=False), sa.Column("institution_name", sa.String(240), nullable=False), sa.Column("degree_name", sa.String(200), server_default=""), sa.Column("field_of_study", sa.String(200), server_default=""), sa.Column("start_date", sa.Date), sa.Column("end_date", sa.Date), sa.Column("gpa", sa.Float), sa.Column("honors", sa.Text, server_default=""), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("credentials", sa.Column("id", sa.Integer, primary_key=True), sa.Column("profile_id", sa.Integer, sa.ForeignKey("profiles.id"), nullable=False), sa.Column("title", sa.String(240), nullable=False), sa.Column("issuer", sa.String(200), server_default=""), sa.Column("issue_date", sa.Date), sa.Column("expiry_date", sa.Date), sa.Column("credential_url", sa.String(500), server_default=""), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("achievements", sa.Column("id", sa.Integer, primary_key=True), sa.Column("experience_id", sa.Integer, sa.ForeignKey("experiences.id"), nullable=False), sa.Column("text", sa.Text, nullable=False), sa.Column("metric_value", sa.String(100), server_default=""), sa.Column("metric_label", sa.String(160), server_default=""), sa.Column("sort_order", sa.Integer, server_default="0"), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))
    op.create_table("project_highlights", sa.Column("id", sa.Integer, primary_key=True), sa.Column("project_id", sa.Integer, sa.ForeignKey("projects.id"), nullable=False), sa.Column("text", sa.Text, nullable=False), sa.Column("metric_value", sa.String(100), server_default=""), sa.Column("metric_label", sa.String(160), server_default=""), sa.Column("sort_order", sa.Integer, server_default="0"), sa.Column("status", status, nullable=False), sa.Column("created_at", sa.DateTime, server_default=sa.func.now()), sa.Column("updated_at", sa.DateTime, server_default=sa.func.now()))

def downgrade():
    for table in ("project_highlights", "achievements", "credentials", "education", "skills", "skill_categories", "projects", "experiences", "admin_users", "profiles"):
        op.drop_table(table)
